### ISSUE TITLE
语法规范有EBNF表达式么？

### ISSUE THREAD

**Issue by linrongbin16** [jadedrip/silang#1]

**Comment by jadedrip** [comment]
还没弄这种东西

**Comment by jadedrip** [comment]
就是自己写着玩的，甚至语法我也还在改……

**Comment by linrongbin16** [comment]
有兴趣的话可以看下我的个人程序设计语言项目：https://github.com/nerd-lang/nerd
前端用flex/bison，后端用llvm
tokenizer: https://github.com/nerd-lang/nerd/blob/master/src/tokenizer.l
parser: https://github.com/nerd-lang/nerd/blob/master/src/parser.y
test case 1: https://github.com/nerd-lang/nerd/blob/master/test/case/parse-1.nerd
test case 2: https://github.com/nerd-lang/nerd/blob/master/test/case/parse-2.nerd
